{% set name = "pyproject2conda" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyproject2conda-{{ version }}.tar.gz
  sha256: 5b7a803601698d038d3bd1c57ece534ed495c886f50694a86ec95e5ca7ec84db

build:
  entry_points:
    - pyproject2conda = pyproject2conda.cli:app
    - p2c = pyproject2conda.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.2
    - setuptools-scm >=7.0
    - pip
  run:
    - python >=3.8
    - tomli
    - ruamel.yaml
    - tomlkit
    - typer
    - packaging
    - typing-extensions

test:
  imports:
    - pyproject2conda
  commands:
    - pip check
    - pyproject2conda --help
    - p2c --help
  requires:
    - pip

about:
  home: https://github.com/usnistgov/pyproject2conda
  summary: A script to convert a Python project declared on a pyproject.toml to a conda environment.
  description: |
    A script to convert a Python project declared on a pyproject.toml to a conda environment.
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
