{% set name = "pyproject2conda" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyproject2conda-{{ version }}.tar.gz
  sha256: 62e0d81bc3cd14c9e8b2281eee2103a88652201acd8b9caaba3bd881bcfd9cbc

build:
  entry_points:
    - pyproject2conda = pyproject2conda.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.2
    - setuptools-scm >=7.0
    - pip
  run:
    - python >=3.8
    - tomli
    - ruamel.yaml
    - tomlkit
    - rich-click
    - packaging

test:
  imports:
    - pyproject2conda
  commands:
    - pip check
    - pyproject2conda --help
  requires:
    - pip

about:
  home: https://github.com/usnistgov/pyproject2conda
  summary:
    A script to convert a Python project declared on a pyproject.toml to a conda
    environment.
  description: |
    A script to convert a Python project declared on a pyproject.toml to a conda environment.
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
